name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        id: scd
        with:
          token: ${{ secrets.PAT }}
          commands: |
            unlock
          issue-type: issue
          permission: none
